### ISSUE TITLE
Font-Family Not Properly Applied in .prose-dante Class

### ISSUE THREAD

**Issue by Leo25190** [JustGoodUI/dante-astro-theme#53]
### 🐛 The Problem

The initial configuration for fontFamily was set as follows:

```cjs
fontFamily: {
    sans: ['ubuntu', ...defaultTheme.fontFamily.sans],
    serif: ['ubuntu', ...defaultTheme.fontFamily.serif]
},
```

However, when applied to headings within the .prose class, the font order was reversed. The generated CSS looked like this:

```css
.prose :where(h1, h2, h3, h4, h5, h6):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
    font-family: ubuntu;
    font-family: ui-serif;
    font-family: Georgia;
    font-family: Cambria;
    font-family: "Times New Roman";
    font-family: Times;
    font-family: serif;
    font-weight: 500;
}
```

The Fix:

To resolve this issue, I updated the fontFamily configuration to use only the ubuntu font:

```cjs
fontFamily: {
    sans: ['ubuntu'],
    serif: ['ubuntu']
},
```

This change ensured that the ubuntu font was consistently applied to all headings within the .prose class.
